wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1672406037.286892
    t:
      1:
      - 1
      - 41
      - 55
      - 63
      - 74
      2:
      - 1
      - 41
      - 55
      - 63
      - 74
      3:
      - 23
      4: 3.10.9
      5: 0.13.7
      8:
      - 5
